version: "3.7"

services:
    postgres-15.7:
        image: postgres:15.7
        command: postgres -c 'max_connections=200'
        environment:
          POSTGRES_DB: bank
          POSTGRES_PASSWORD: "12345"
        ports:
        - "5436:5432"
        volumes:
        - postgres:/var/lib/postgresql/data
        networks:
        - network-local

    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2182
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2182:2182"

    kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


volumes:
    postgres:
        driver: local
    cassandra:
    kafka_data:

networks:
    network-local:
        driver: bridge
