spring:
  application:
    name: bank-core-service
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: bank-group
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
    producer:
      bootstrap-servers: localhost:9093

logging:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml